import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const versionFile = path.join(root, 'VERSION');
const version = fs.readFileSync(versionFile, 'utf8').trim();
if (!version) {
  throw new Error('VERSION file is empty');
}

function writeIfChanged(filePath, next) {
  const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (prev === next) return false;
  fs.writeFileSync(filePath, next);
  return true;
}

function updateJson(relPath, mutate) {
  const filePath = path.join(root, relPath);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  mutate(data);
  writeIfChanged(filePath, JSON.stringify(data, null, 2) + '\n');
}

function updateTomlVersion(relPath) {
  const filePath = path.join(root, relPath);
  const prev = fs.readFileSync(filePath, 'utf8');
  const next = prev.replace(/(^version\s*=\s*")([^"]+)("\s*$)/m, `$1${version}$3`);
  if (next === prev) return false;
  fs.writeFileSync(filePath, next);
  return true;
}

updateJson('package.json', (data) => {
  data.version = version;
});

updateJson('package-lock.json', (data) => {
  data.version = version;
  if (data.packages && data.packages['']) {
    data.packages[''].version = version;
  }
});

updateJson('src-tauri/tauri.conf.json', (data) => {
  data.version = version;
});

updateTomlVersion('src-tauri/Cargo.toml');

writeIfChanged(
  path.join(root, 'src/lib/app-version.ts'),
  `// Generated by scripts/sync-version.mjs from VERSION. Do not edit manually.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
);

console.log(`Synced desktop app version to ${version}`);
